Resources:
  HelloHandlerServiceRole11EF7C63:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHandler/ServiceRole/Resource
  HelloHandler2E4FBA4D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3Bucket3D730968
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3VersionKey13D58A7F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3VersionKey13D58A7F
      Handler: hello.handler
      Role:
        Fn::GetAtt:
          - HelloHandlerServiceRole11EF7C63
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - HelloHandlerServiceRole11EF7C63
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHandler/Resource
      aws:asset:path: asset.82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73a
      aws:asset:property: Code
  HelloHitCounterHits7AAEBF80:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHitCounter/Hits/Resource
  HelloHitCounterHitCounterHandlerServiceRoleD45002B8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHitCounter/HitCounterHandler/ServiceRole/Resource
  HelloHitCounterHitCounterHandlerServiceRoleDefaultPolicy1487A60A:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - HelloHitCounterHits7AAEBF80
                  - Arn
              - Ref: AWS::NoValue
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - HelloHandler2E4FBA4D
                - Arn
        Version: "2012-10-17"
      PolicyName: HelloHitCounterHitCounterHandlerServiceRoleDefaultPolicy1487A60A
      Roles:
        - Ref: HelloHitCounterHitCounterHandlerServiceRoleD45002B8
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHitCounter/HitCounterHandler/ServiceRole/DefaultPolicy/Resource
  HelloHitCounterHitCounterHandlerDAEA7B37:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3Bucket3D730968
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3VersionKey13D58A7F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3VersionKey13D58A7F
      Handler: hitcounter.handler
      Role:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerServiceRoleD45002B8
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          DOWNSTREAM_FUNCTION_NAME:
            Ref: HelloHandler2E4FBA4D
          HITS_TABLE_NAME:
            Ref: HelloHitCounterHits7AAEBF80
    DependsOn:
      - HelloHitCounterHitCounterHandlerServiceRoleDefaultPolicy1487A60A
      - HelloHitCounterHitCounterHandlerServiceRoleD45002B8
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/HelloHitCounter/HitCounterHandler/Resource
      aws:asset:path: asset.82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73a
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Account
  EndpointDeployment318525DA5caa73f0d975d65bd435d06541de11d8:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DA5caa73f0d975d65bd435d06541de11d8
      StageName: prod
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionAwsCdkWorkshopStackEndpoint483FDF45ANYproxy66690C7A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.AwsCdkWorkshopStackEndpoint483FDF45.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestAwsCdkWorkshopStackEndpoint483FDF45ANYproxy5CC15223:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.AwsCdkWorkshopStackEndpoint483FDF45.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloHitCounterHitCounterHandlerDAEA7B37
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionAwsCdkWorkshopStackEndpoint483FDF45ANY478E3E9A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/ANY/ApiPermission.AwsCdkWorkshopStackEndpoint483FDF45.ANY..
  EndpointANYApiPermissionTestAwsCdkWorkshopStackEndpoint483FDF45ANY23AAF848:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/ANY/ApiPermission.Test.AwsCdkWorkshopStackEndpoint483FDF45.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloHitCounterHitCounterHandlerDAEA7B37
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: AwsCdkWorkshopStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.64.1,@aws-cdk/assets=1.64.1,@aws-cdk/aws-apigateway=1.64.1,@aws-cdk/aws-applicationautoscaling=1.64.1,@aws-cdk/aws-autoscaling-common=1.64.1,@aws-cdk/aws-cloudwatch=1.64.1,@aws-cdk/aws-codeguruprofiler=1.64.1,@aws-cdk/aws-dynamodb=1.64.1,@aws-cdk/aws-ec2=1.64.1,@aws-cdk/aws-events=1.64.1,@aws-cdk/aws-iam=1.64.1,@aws-cdk/aws-kms=1.64.1,@aws-cdk/aws-lambda=1.64.1,@aws-cdk/aws-logs=1.64.1,@aws-cdk/aws-s3=1.64.1,@aws-cdk/aws-s3-assets=1.64.1,@aws-cdk/aws-sqs=1.64.1,@aws-cdk/aws-ssm=1.64.1,@aws-cdk/cloud-assembly-schema=1.64.1,@aws-cdk/core=1.64.1,@aws-cdk/custom-resources=1.64.1,@aws-cdk/cx-api=1.64.1,@aws-cdk/region-info=1.64.1,jsii-runtime=node.js/v12.18.4
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3Bucket3D730968:
    Type: String
    Description: S3 bucket for asset "82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73a"
  AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aS3VersionKey13D58A7F:
    Type: String
    Description: S3 key for asset version "82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73a"
  AssetParameters82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73aArtifactHash7097F0D1:
    Type: String
    Description: Artifact hash for asset "82b68be76a76c15a4fe0332c5f1b28442aa7a52fa9f00e7fc3b512304370e73a"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

